run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
      print-issued-lines: true
      print-linter-name: true

linters-settings:
  depguard:
    rules:
      Main:
        files:
          - $all
        allow:
          - $gostd
          - github.com/vector233/go-singpass
          - github.com/lestrrat-go/jwx/v3
          - github.com/lestrrat-go/httprc/v3
          - github.com/redis/go-redis/v9
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/vector233/go-singpass)
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/your-username/go-singpass
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
  govet:
    enable:
      - shadow
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$"
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gocyclo
    - path: example/
      linters:
        - mnd
        - revive
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - mnd
      text: "Magic number.*in <(assign|operation|argument)> detected"
  exclude:
    - 'declaration of "err" shadows declaration at'
    - 'G104: Errors unhandled'
    - 'unused-parameter.*consider removing or renaming it as _'
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false